Repository AY2324S1-CS2113T-W11-2/tp, pull requests merged in 2023-11, with the labels that each got.

#113 Organize all classes into their respective packages for modularity
  src/main/java/seedu/wildwatch/WildWatch.java
  src/main/java/seedu/wildwatch/command/AddCommand.java
  src/main/java/seedu/wildwatch/command/ByeCommand.java
  src/main/java/seedu/wildwatch/command/DeleteCommand.java
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/command/FindCommand.java
  src/main/java/seedu/wildwatch/command/ListCommand.java
  src/main/java/seedu/wildwatch/command/SummaryCommand.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/error/DateChecker.java
  src/main/java/seedu/wildwatch/error/ErrorChecker.java
  src/main/java/seedu/wildwatch/error/ErrorHandler.java
  src/main/java/seedu/wildwatch/error/InvalidInputErrorType.java
  src/main/java/seedu/wildwatch/exception/InvalidInputException.java
  src/main/java/seedu/wildwatch/input/CommandHandler.java
  src/main/java/seedu/wildwatch/input/InputHandler.java
  src/main/java/seedu/wildwatch/miscellaneous/BootUp.java
  src/main/java/seedu/wildwatch/miscellaneous/LogHandler.java
  src/main/java/seedu/wildwatch/miscellaneous/ShutDown.java
  src/main/java/seedu/wildwatch/operation/Ui.java
  src/main/java/seedu/wildwatch/parser/AddCommandParser.java
  src/main/java/seedu/wildwatch/parser/DeleteCommandParser.java
  src/main/java/seedu/wildwatch/parser/FileStringParser.java
  src/main/java/seedu/wildwatch/parser/FindCommandParser.java
  src/main/java/seedu/wildwatch/storage/EntryToStringConverter.java
  src/main/java/seedu/wildwatch/storage/ExistenceChecker.java
  src/main/java/seedu/wildwatch/storage/FileCreater.java
  src/main/java/seedu/wildwatch/storage/FileHandler.java
  src/main/java/seedu/wildwatch/storage/FileLoader.java
  src/main/java/seedu/wildwatch/storage/Saver.java
  src/main/java/seedu/wildwatch/ui/AddCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/DeleteCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/EditCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/EmptyDescriptionPrinter.java
  src/main/java/seedu/wildwatch/ui/EntryPrinter.java
  src/main/java/seedu/wildwatch/ui/ErrorPrinter.java
  src/main/java/seedu/wildwatch/ui/FilePrinter.java
  src/main/java/seedu/wildwatch/ui/InputReceiver.java
  src/main/java/seedu/wildwatch/ui/LinePrinter.java
  src/main/java/seedu/wildwatch/ui/ListCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/SearchResultPrinter.java
  src/main/java/seedu/wildwatch/ui/SummaryCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/Ui.java
  src/test/java/seedu/wildwatch/input/DateCheckerTest.java
  src/test/java/seedu/wildwatch/input/EntryHandlerTest.java
  src/test/java/seedu/wildwatch/operation/DateHandlerTest.java
  src/test/java/seedu/wildwatch/parser/AddCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#130 Create EditCommandParser class for more robust exception handling
  docs/diagrams/HelpCommand.puml
  src/main/java/seedu/wildwatch/WildWatch.java
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/command/HelpCommand.java
  src/main/java/seedu/wildwatch/command/SummaryCommand.java
  src/main/java/seedu/wildwatch/entry/Entry.java
  src/main/java/seedu/wildwatch/error/ErrorChecker.java
  src/main/java/seedu/wildwatch/error/ErrorHandler.java
  src/main/java/seedu/wildwatch/error/InvalidInputErrorType.java
  src/main/java/seedu/wildwatch/execute/CommandHandler.java
  src/main/java/seedu/wildwatch/execute/InputHandler.java
  src/main/java/seedu/wildwatch/miscellaneous/ShutDown.java
  src/main/java/seedu/wildwatch/parser/AddCommandParser.java
  src/main/java/seedu/wildwatch/parser/DeleteCommandParser.java
  src/main/java/seedu/wildwatch/parser/EditCommandParser.java
  src/main/java/seedu/wildwatch/parser/FileStringParser.java
  src/main/java/seedu/wildwatch/storage/FileHandler.java
  src/main/java/seedu/wildwatch/ui/DeleteCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/EmptyDescriptionPrinter.java
  src/main/java/seedu/wildwatch/ui/ErrorPrinter.java
Labels: priority.High, type.Operation, type.Enhancement

#131 Rename ErrorChecker to Router
  src/main/java/seedu/wildwatch/error/DateChecker.java
  src/main/java/seedu/wildwatch/error/Router.java
  src/main/java/seedu/wildwatch/exception/EmptyInputException.java
  src/main/java/seedu/wildwatch/exception/EmptyListException.java
  src/main/java/seedu/wildwatch/exception/EntryNotFoundException.java
  src/main/java/seedu/wildwatch/execute/CommandHandler.java
  src/main/java/seedu/wildwatch/parser/EditCommandParser.java
  src/test/java/seedu/wildwatch/execute/EntryHandlerTest.java
Labels: priority.Medium

#178 Create FindCommandParserTest
  src/main/java/seedu/wildwatch/command/FindCommand.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/execute/CommandHandler.java
  src/main/java/seedu/wildwatch/execute/InputHandler.java
  src/main/java/seedu/wildwatch/execute/Router.java
  src/main/java/seedu/wildwatch/parser/EditCommandParser.java
  src/main/java/seedu/wildwatch/parser/FindCommandParser.java
  src/main/java/seedu/wildwatch/storage/EntryToStringConverter.java
  src/main/java/seedu/wildwatch/storage/ExistenceChecker.java
  src/main/java/seedu/wildwatch/storage/FileCreater.java
  src/main/java/seedu/wildwatch/storage/FileLoader.java
  src/main/java/seedu/wildwatch/storage/Saver.java
  src/main/java/seedu/wildwatch/ui/InputPromptPrinter.java
  src/test/java/seedu/wildwatch/command/AddCommandTest.java
  src/test/java/seedu/wildwatch/command/DeleteCommandTest.java
  src/test/java/seedu/wildwatch/command/ListCommandTest.java
  src/test/java/seedu/wildwatch/execute/DateCheckerTest.java
  src/test/java/seedu/wildwatch/execute/EntryHandlerTest.java
  src/test/java/seedu/wildwatch/execute/RouterTest.java
  src/test/java/seedu/wildwatch/parser/AddCommandParserTest.java
  src/test/java/seedu/wildwatch/parser/FindCommandParserTest.java
Labels: priority.Medium, type.Test

#179 Create EntryListTest
  build.gradle
  src/main/java/seedu/wildwatch/entry/Entry.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/storage/Saver.java
  src/test/java/seedu/wildwatch/command/AddCommandTest.java
  src/test/java/seedu/wildwatch/command/DeleteCommandTest.java
  src/test/java/seedu/wildwatch/entry/EntryListTest.java
  src/test/java/seedu/wildwatch/entry/EntryTest.java
  src/test/java/seedu/wildwatch/execute/RouterTest.java
Labels: priority.Medium, type.Test

#184 Create EditCommandTest
  build.gradle
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/test/java/seedu/wildwatch/command/EditCommandTest.java
  src/test/java/seedu/wildwatch/entry/EntryListTest.java
  src/test/java/seedu/wildwatch/entry/EntryTest.java
  src/test/java/seedu/wildwatch/error/ErrorHandlerTest.java
  src/test/java/seedu/wildwatch/execute/DateCheckerTest.java
  src/test/java/seedu/wildwatch/execute/RouterTest.java
  src/test/java/seedu/wildwatch/parser/FindCommandParserTest.java
Labels: priority.High, type.Test

#192 Fix bug: [PE-D][Tester B] List function executed whenever with leadin…
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/error/DateChecker.java
  src/main/java/seedu/wildwatch/execute/Router.java
  src/main/java/seedu/wildwatch/parser/EditCommandParser.java
  src/main/java/seedu/wildwatch/parser/ListCommandParser.java
Labels: priority.High, type.Review

#194 Create InputConsoleTest
  src/test/java/seedu/wildwatch/command/DeleteCommandTest.java
  src/test/java/seedu/wildwatch/error/ErrorHandlerTest.java
  src/test/java/seedu/wildwatch/ui/EmptyDescriptionPrinterTest.java
  src/test/java/seedu/wildwatch/ui/EntryPrinterTest.java
  src/test/java/seedu/wildwatch/ui/InputConsoleTest.java
Labels: priority.Medium, type.Test

#199 Fix indentation error in HelpCommand.java
  src/main/java/seedu/wildwatch/command/HelpCommand.java
Labels: priority.High, type.Enhancement

#201 Fix bug: [PE-D][Tester B] Failed to further validate yes/no choice for delete function #151
  src/main/java/seedu/wildwatch/command/AddCommand.java
  src/main/java/seedu/wildwatch/command/DeleteCommand.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/ui/DeleteCommandPrinter.java
  src/main/java/seedu/wildwatch/ui/SearchResultPrinter.java
  src/test/java/seedu/wildwatch/entry/EntryListTest.java
Labels: priority.Medium, type.Operation

#208 Update 'tasks' to 'entries' in files
  src/main/java/seedu/wildwatch/storage/FileHandler.java
  src/main/java/seedu/wildwatch/ui/FilePrinter.java
  src/main/java/seedu/wildwatch/ui/InputPromptPrinter.java
  src/main/java/seedu/wildwatch/ui/SearchResultPrinter.java
Labels: priority.High, type.Docs

#213 Fix naming of hasSpecies method
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/parser/SummaryCommandParser.java
Labels: priority.Low, type.Operation

#214 Change <DATE> to DD-MM-YYYY
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/wildwatch/command/FindCommand.java
  src/main/java/seedu/wildwatch/command/HelpCommand.java
  src/main/java/seedu/wildwatch/entry/Entry.java
  src/main/java/seedu/wildwatch/error/DateChecker.java
  src/main/java/seedu/wildwatch/storage/EntryToStringConverter.java
  src/main/java/seedu/wildwatch/ui/SearchResultPrinter.java
  src/test/java/seedu/wildwatch/command/AddCommandTest.java
  src/test/java/seedu/wildwatch/command/DeleteCommandTest.java
  src/test/java/seedu/wildwatch/command/EditCommandTest.java
  src/test/java/seedu/wildwatch/command/ListCommandTest.java
  src/test/java/seedu/wildwatch/entry/EntryListTest.java
  src/test/java/seedu/wildwatch/entry/EntryTest.java
  src/test/java/seedu/wildwatch/execute/DateCheckerTest.java
  src/test/java/seedu/wildwatch/execute/RouterTest.java
  src/test/java/seedu/wildwatch/parser/AddCommandParserTest.java
  src/test/java/seedu/wildwatch/parser/FindCommandParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#215 Update Help Page according to the update in the UG
  src/main/java/seedu/wildwatch/command/HelpCommand.java
Labels: priority.High, type.Docs

#216 Update Help Page according to the update in the UG
  src/main/java/seedu/wildwatch/command/HelpCommand.java
Labels: priority.High, type.Operation

#217 Change from 1 entries to 1 entry #212
  src/main/java/seedu/wildwatch/ui/ListCommandPrinter.java
  src/test/java/seedu/wildwatch/command/ListCommandTest.java
Labels: priority.Low, type.Operation

#204 Check duplicate entry
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/parser/AddCommandParser.java
  src/main/java/seedu/wildwatch/parser/FileStringParser.java
Labels: priority.Medium, type.Enhancement, type.Review

#207 Modify summary command to list entries
  src/main/java/seedu/wildwatch/command/SummaryCommand.java
  src/main/java/seedu/wildwatch/entry/Entry.java
Labels: priority.Low, type.Enhancement, type.Review

#220 Rectify spelling errors in SummaryCommandParser
  WildWatch.log.2
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/command/SummaryCommand.java
  src/main/java/seedu/wildwatch/parser/SummaryCommandParser.java
Labels: priority.Medium, type.Operation

#221 Update code standards in EditCommand
  src/main/java/seedu/wildwatch/command/EditCommand.java
  src/main/java/seedu/wildwatch/command/ExportCommand.java
  src/main/java/seedu/wildwatch/miscellaneous/BootUp.java
  src/main/java/seedu/wildwatch/storage/ExistenceChecker.java
  src/main/java/seedu/wildwatch/storage/FileCreator.java
  src/main/java/seedu/wildwatch/storage/FileHandler.java
  src/main/java/seedu/wildwatch/ui/FilePrinter.java
Labels: priority.High, type.Enhancement

#226 Update SummaryCommand to not be case-sensitive
  src/main/java/seedu/wildwatch/command/SummaryCommand.java
  src/main/java/seedu/wildwatch/entry/EntryList.java
  src/main/java/seedu/wildwatch/parser/SummaryCommandParser.java
Labels: priority.Medium, type.Enhancement

#227 Update HelpCommand to include UG
  src/main/java/seedu/wildwatch/command/HelpCommand.java
Labels: priority.Low, type.Operation

#228 Update HelpCommand to include Interactive Add Command
  src/main/java/seedu/wildwatch/command/HelpCommand.java
Labels: priority.High, type.Command
